[package]
name = "container"
version = "0.2.0"
authors = ["Curtis Millar <curtis@curtism.me>"]

[dependencies]
nix = "0.11.0"
error-chain = "0.11.0"
loadconf = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
unshare = "0.2.0"
libc = "0.2"
