#![allow(missing_docs)]

//! Errors generated by isolate.
error_chain!{
    // Wrappers for other error_chains.
    links {
    }

    // Wrappers for other errors.
    foreign_links {
        Io(::std::io::Error);
        Nul(::std::ffi::NulError);
        Utf8(::std::str::Utf8Error);
        Nix(::nix::Error);
        Unshare(::unshare::Error);
    }

    // Internally defined errors.
    errors {
        UnshareExit {
            description("The unshared was unsuccessful.")
        }
        CommandExit {
            description("The requested command was unsuccessful.")
        }
    }
}

pub type Failure = Result<()>;

macro_rules! ok { () => (Ok(())) }
